### ISSUE TITLE
Update compositions using Palindrom flow

### ISSUE THREAD

**Issue by tomalec** [Starcounter/CompositionProvider#12]
Currently we are using legacy REST API that was use d as a workaround for set of issues, hopefully, we can finally get rid of it, and use regular Palindrom flow.

**Comment by tomalec** [comment]
This issue blocks https://github.com/Starcounter/starcounter-include/issues/42

**Comment by tomalec** [comment]
Changes in Editor, and starcounter-include should follow after this one.

**Comment by warpech** [comment]
Great change! But wow can I test if it works? 

I propose to test it with changes in CompositionEditor.

Also, this makes https://github.com/StarcounterApps/CompositionEditor/issues/31 more important.

**Comment by tomalec** [comment]
I'm currently working on bulk change for the editor to make it work with the new starcounter-include https://github.com/Starcounter/starcounter-include/issues/42

**Comment by tomalec** [comment]
You can test it by trying `document.querySelector('puppet-client').obj.CurrentPage.CompositionProvider.Composition$ = 'something'` in console. Then clicking somewherein the page (trigger Puppet change)

**Comment by warpech** [comment]
This is now implemented. The new compositions are saved using Palindrom, not using REST.
