### ISSUE TITLE
Invalid MainView for Html composition when no Html field

### ISSUE THREAD

**Issue by un-tone** [Starcounter/CompositionProvider#18]
### Steps to reproduce

1. Run WebsiteProvider, WebsiteEditor, CompositionProvider, SignIn
1. Go to <http://localhost:8080/websiteeditor>
1. Open Starcounter DevTools and check CompositionProvider JSON tree for TopBar blending point

### Expected result

`PartialId` is `<some_uri_for_main_json>|/SignIn/views/SignInPage.html`

### Actual result

`PartialId` is `/SignIn/views/SignInPage.html`

### Screenshot
![image](https://user-images.githubusercontent.com/1625378/33774217-9988b59e-dc4b-11e7-88f8-62762a10eb6f.png)

### Technical information

If we have a handler which returns a JSON without Html field, e.g. the following:

```csharp
Handle.GET(callerUri, () => new Json());
```

and mapped with other handlers which return correct JSONs with Html field, then when we call that `callerUri` with `Self.GET`, CompositionProvider builds incorrect composition key because it defines an incorrect main view for the composition since the actual "main" JSON does not have Html field.

This is incorrect because after saving such composition it can be mistakenly used for cases when `/SignIn/views/SignInPage.html` is the actual main view. CompositionProvider builds `PartialId` by concatenating of all views' URIs, but inserting the main view at the beginning.

I'm not sure what `<some_uri_for_main_json>` we should use for such JSONs without Html fields.

In my example, we have the following URIs which are called:

* `/websiteprovider/blender/surface/B/point/C` - called by `Self.GET` and doesn't have Html field
* `/signin/user` - provides `/SignIn/views/SignInPage.html` view.

Maybe we could use `/websiteprovider/blender/surface/B/point/C` for main JSON URI, but it contains IDs for surface and blending point.

@Starcounter/webplatformteam WDYT?

**Comment by warpech** [comment]
@PatrykSzwer can you think if this is a good solution? 

I think that it's OK and desired in this case that the URI it contains IDs for surface and blending point.

**Comment by un-tone** [comment]
Please take a look at #19 PR. WDYT?

**Comment by un-tone** [comment]
Closing as done
