### ISSUE TITLE
Can't save styles

### ISSUE THREAD

**Issue by papusa** [Starcounter/CompositionProvider#6]
### Steps to reproduce
- Added "Images" to our application
- Open composition editor
- Tried to add some new styles to [slot="Images/current-page"]
- Press save button in editor

### Expected result

New styles should be saved and not disappear after page refresh

### Actual result

After refreshing the page new styles are no more applied. However, markup gets saved in database with "Key" set to null

![image](https://cloud.githubusercontent.com/assets/23210354/24298349/6abbf898-10ae-11e7-8300-619ea51bbbfa.png)

### Technical information

All necessary apps were up and running:

![image](https://cloud.githubusercontent.com/assets/23210354/24298457/bbced1f6-10ae-11e7-9b42-472c9d2d15c3.png)

##### Starcounter version 

Starcounter-RC-2.3.0.6107

##### Involved apps' version

 - CompositionEditor 1.1.0, 1.1.2,  1.1.3, (tried 3 different versions)
 - CompositionProvider: 1.0.0
 - Images 3.1.0

 
##### Browsers affected

- [x] Chrome

### Screenshot

![image](https://cloud.githubusercontent.com/assets/23210354/24298631/42ffbeb0-10af-11e7-9521-c25a6384600e.png)

**Comment by warpech** [comment]
Thanks for the issue. We will investigate.

**Comment by warpech** [comment]
I can reproduce it with our sample apps:

1. Start HelloWorld + Images + HelloWorldMapper + CompositionEditor + CompositionProvider
2. Add some expense and upload an image
3. Press CTRL+E to open the composition editor
4. Double click the input and select `[slot="Images/current-page"]`
5. Change something and press Save$

![2017-03-27 16_59_26-helloworld](https://cloud.githubusercontent.com/assets/566463/24362984/c0b76482-130e-11e7-8b31-7352d516a250.png)

**Comment by tomalec** [comment]
I do so with Products + Images +  CompositionEditor + CompositionProvider.

It seems that merged `CurrentPage` from Images, does not have `PartialId` nor  any `LayoutInfo`, etc. I continue investigation/

**Comment by TakhirMamirov** [comment]
Do you have any progress on the issue?

**Comment by tomalec** [comment]
Yes, I've made a quick fix at Images app https://github.com/StarcounterApps/Images/commit/9f27b187bb4a7504d600eabf2cbd2adb10751974.
Today I'll try to prepare more complete fix for Images app.

You can already check if it solves the problem for you. If not maybe there is a similar  problem in your app. Feel free to contact me via hangouts or email.

**Comment by papusa** [comment]
@tomalec, is that fix available in Starcounter App Warehouse? I mean fixed version of Images app.
Thanks

**Comment by tomalec** [comment]
not yet, for that quickfix, you will have to clone/pull the repo https://github.com/StarcounterApps/Images, build and run it manually https://github.com/StarcounterApps/Images

The proper fix I was talking about will be released as a new version in Warehouse

**Comment by tomalec** [comment]
@papusa Pleas check 3.1.1 in Warehouse

**Comment by papusa** [comment]
@tomalec, it works :)
